version: '3.8'
services:
  postgres_db:
    image: postgres:12.11
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: persons
    ports:
      - '5432:5432'