version: '3.8'
services:
  postgres_db:
    image: postgres:12.11
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test123.MW
      POSTGRES_DB: persons
    ports:
      - '5433:5432'